- rm_hw/include/rm_hw/control_loop.h
- rm_hw/include/rm_hw/hardware_interface/hardware_interface.h
- rm_hw/include/rm_hw/transmission/double_actuator_transmission.h
- rm_hw/include/rm_hw/transmission/double_actuator_transmission_loader.h
…h, double_actuator_transmission_loader.h.
> Add doxygen comments on control_loop and transmission

- rm_hw/src/hardware_interface/can_bus.cpp
> Delete contents in brackets

- rm_common/src/filter/imu_complementary_filter.cpp
> Fix a bug in loading params of imu filter

- rm_msgs/CMakeLists.txt
- rm_msgs/msg/detection/TrackCmd.msg
> Add TrackCmd.msg

- rm_common/include/rm_common/linear_interpolation.h
单独编译rm_common不会报错。。甚至不会有warning。但是编译rm_manual时会报错
> Fix a stupid bug

- rm_hw/include/rm_hw/hardware_interface/types.h
- rm_hw/src/hardware_interface/can_bus.cpp
- rm_hw/src/hardware_interface/parse.cpp
> Add imu angular_vel_offset.

- rm_referee/include/rm_referee/referee_base.h
- rm_referee/include/rm_referee/ui/time_change_ui.h
- rm_referee/src/referee_base.cpp
- rm_referee/src/ui/time_change_ui.cpp
> Add lane line ui.

- rm_common/CMakeLists.txt
- rm_common/package.xml
- rm_dbus/CMakeLists.txt
- rm_dbus/package.xml
- rm_gazebo/CMakeLists.txt
- rm_gazebo/package.xml
- rm_hw/CMakeLists.txt
- rm_hw/package.xml
- rm_referee/CMakeLists.txt
- rm_referee/package.xml
删除了cmakelist和package.xml里的roslint依赖
> Delete dependence roslint.

- rm_common/include/rm_common/decision/command_sender.h
新增了一个command sender的类，用于在manual中通过按键切换相机；因为英雄现在使用两个相机，实现切换相机的方法是：向一个话题发布一个字符串，根据这个字符串决定使用哪个相机。
> Add a command serder class for switching camera.

- .github/workflows/format.yml
- rm_common/include/rm_common/decision/command_sender.h
- rm_referee/include/rm_referee/common/data.h
- rm_referee/include/rm_referee/referee_base.h
- rm_referee/include/rm_referee/ui/graph.h
- rm_referee/include/rm_referee/ui/trigger_change_ui.h
- rm_referee/include/rm_referee/ui/ui_base.h
- rm_referee/src/referee.cpp
- rm_referee/src/referee_base.cpp
- rm_referee/src/ui/trigger_change_ui.cpp
- rm_referee/src/ui/ui_base.cpp
一个通过读取/track获得敌方id并将敌方血量画在屏幕上的ui。
本ui配套的参数：
- name: "blood_volume"
config: { start_position: [ 820, 800 ], size: 15, width: 2 }
> Add blood volume ui.

- rm_common/include/rm_common/decision/command_sender.h
- rm_common/include/rm_common/decision/power_limit.h
- rm_msgs/README.md
- rm_msgs/msg/ChassisCmd.msg
- rm_referee/src/ui/flash_ui.cpp
- rm_referee/src/ui/trigger_change_ui.cpp
> Delete the chassis mode "GYRO"

- rm_common/include/rm_common/decision/power_limit.h
修改电容离线时的功率限制，使当电容离线时仍可以使用缓冲能量。
> Modify the power limit when the capacitor is offline.

- rm_common/include/rm_common/decision/heat_limit.h
> Add two function to get data about cooling.

- rm_referee/include/rm_referee/referee.h
- rm_referee/src/referee.cpp
添加一个发布者用于发布哨兵在裁判系统上收到的目标点，用于重新设置哨兵的目标点。
> Add a publisher to send target position from serial.

- rm_msgs/msg/detection/TargetDetection.msg
> Added parameters describing the type of armor plate.

- rm_referee/include/rm_referee/referee.h
- rm_referee/src/referee.cpp
> Modify the publisher name.

- rm_common/include/rm_common/decision/command_sender.h
- rm_msgs/CMakeLists.txt
- rm_msgs/msg/MultiDofCmd.msg
> Add MultiDofCommandSender for multi_dof_controller.

- rm_referee/src/ui/trigger_change_ui.cpp
> Update big buff and small buff ui.

- rm_common/include/rm_common/decision/service_caller.h
> Add a function to set target type.

- rm_msgs/msg/referee/ClientMapSendData.msg
> Add key u for sentry fsm.

- rm_common/include/rm_common/decision/heat_limit.h
增加一个最低射频，用于打符时通过manual设置一个低射频。
> Add minimal shoot frequency for hitting buff.

- rm_common/include/rm_common/decision/service_caller.h
- rm_msgs/srv/StatusChange.srv
- rm_referee/include/rm_referee/referee_base.h
- rm_referee/include/rm_referee/ui/time_change_ui.h
- rm_referee/src/referee_base.cpp
- rm_referee/src/ui/time_change_ui.cpp
> Add pitch angle ui for hero

- rm_msgs/CMakeLists.txt
- rm_msgs/msg/detection/ExchangerMsg.msg
- rm_msgs/msg/referee/EngineerUi.msg
- rm_referee/include/rm_referee/common/data.h
- rm_referee/include/rm_referee/referee_base.h
- rm_referee/include/rm_referee/ui/trigger_change_ui.h
- rm_referee/src/referee_base.cpp
- rm_referee/src/ui/time_change_ui.cpp
- rm_referee/src/ui/trigger_change_ui.cpp
将之前旧时候的工程ui经过修改之后合并到新的control里
> Merge the engineer's ui into master

- rm_referee/include/rm_referee/referee_base.h
- rm_referee/include/rm_referee/ui/ui_base.h
- rm_referee/src/referee_base.cpp
- rm_referee/src/ui/ui_base.cpp
添加小地图接收信息：referee命令码0x0305
雷达站发送的坐标信息可以被所有己方操作手在第一视角小地图看到。
> Add radar interactive

- rm_msgs/msg/referee/PowerManagementSampleAndStatusData.msg
- rm_referee/include/rm_referee/common/data.h
- rm_referee/include/rm_referee/common/protocol.h
- rm_referee/include/rm_referee/referee.h
- rm_referee/src/referee.cpp
> Update PowerManagement protocol v1.2

- rm_referee/src/referee_base.cpp
更新chassis command sender发布的话题名字
> Update chassis topic.

- rm_msgs/msg/referee/ClientMapSendData.msg
增加一个按键，在哨兵卡到静态障碍的时候也可以让哨兵往一个点的位置移动
> Add KEY_H for sentry to force run out.

- rm_msgs/CMakeLists.txt
- rm_msgs/msg/referee/PowerManagementProcessStackOverflowData.msg
- rm_msgs/msg/referee/PowerManagementSystemExceptionData.msg
- rm_msgs/msg/referee/PowerManagementUnknownExceptionData.msg
- rm_referee/include/rm_referee/common/data.h
- rm_referee/include/rm_referee/common/protocol.h
- rm_referee/include/rm_referee/referee.h
- rm_referee/src/referee.cpp
> Add other unpack code for power management

- rm_referee/include/rm_referee/ui/flash_ui.h
- rm_referee/include/rm_referee/ui/trigger_change_ui.h
- rm_referee/include/rm_referee/ui/ui_base.h
- rm_referee/src/referee_base.cpp
- rm_referee/src/ui/ui_base.cpp
修改了机器人加ui的逻辑
原有的逻辑是短时间内发送大量ui，这种方式在平衡1上导致调can，推测可能是触发串口中断过于频繁导致寄存器溢出错误。目前修改add ui方式为队列。
> Adjust UI add logic

- rm_msgs/srv/EnableGyro.srv
- rm_msgs/srv/SetLimitVel.srv
> Modify type of srv

- rm_dbus/include/rm_dbus/dbus.h
- rm_dbus/src/dbus.cpp
- rm_dbus/src/dbus_node.cpp
> Update switch debouncing.

- .github/workflows/deb_package.yml
update action to deploy deb package to our new server.
> update action Deb_package to work with new server

- rm_msgs/msg/detection/TargetDetectionArray.msg
> Add is_red flag in TargetDetectionArray.msg.

- rm_msgs/msg/referee/EngineerUi.msg
- rm_referee/include/rm_referee/referee_base.h
- rm_referee/include/rm_referee/ui/flash_ui.h
- rm_referee/src/referee_base.cpp
- rm_referee/src/ui/flash_ui.cpp
添加工程动作组ui，根据msg中的symbol来画不同的ui
> Add engineer action ui.

- rm_common/include/rm_common/decision/command_sender.h
- rm_common/include/rm_common/decision/heat_limit.h
- rm_msgs/CMakeLists.txt
- rm_msgs/msg/LocalHeatState.msg
Reverts rm-controls/rm_control#223
> Revert "Calculate local heat. "

- rm_common/include/rm_common/decision/power_limit.h
- rm_msgs/msg/referee/PowerManagementSampleAndStatusData.msg
- rm_referee/include/rm_referee/ui/trigger_change_ui.h
- rm_referee/src/referee.cpp
- rm_referee/src/ui/trigger_change_ui.cpp
> Update new capacitor control code.

- rm_common/include/rm_common/decision/command_sender.h
加入一个能够改变位置的函数，适配英雄图传或倍镜控制器的位置微调。
> Add the function of change position

- rm_common/include/rm_common/decision/command_sender.h
- rm_msgs/msg/referee/DartClientCmd.msg
- rm_msgs/msg/referee/RfidStatus.msg
- rm_referee/include/rm_referee/common/protocol.h
- rm_referee/src/referee.cpp
> Update referee protocol

- rm_common/include/rm_common/decision/command_sender.h
> Optimize the method for adjusting wheel speed in deploy mode
